#!/bin/bash
# This script is used for testing docker image generating
# in development environment.
#
# Usage:
#
# ./docker/make-image

DOCKER_BUILDKIT=1 \
  docker build \
  --build-arg HEX_MIRROR_URL \
  --build-arg NPM_REGISTRY \
  --build-arg APPSIGNAL_HTTP_PROXY \
  --build-arg SASS_BINARY_SITE \
  --build-arg MIX_ENV=prod \
  -t bonfire \
  --target release_image \
  $@ \
  .
